# Generated by Django 3.2.7 on 2021-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocupacion', models.CharField(max_length=40, verbose_name='Ocupacion')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('edad', models.IntegerField()),
                ('resguardo', models.CharField(max_length=45, verbose_name='Resguardo_o_Ciudad')),
                ('etnia', models.CharField(max_length=45, verbose_name='Etnia')),
                ('departamento', models.CharField(max_length=45, verbose_name='Departamento_Residencia')),
            ],
        ),
    ]
