from .personaSerializer import PersonaSerializer
from .usuarioSerializer import UserSerializer
from .ocupacionSerializer import OcupacionSerializer
from .etniaSerializer import EtniaSerializer
from .resguardoSerializer import ResguardoSerializer